Makefile
@tomwilkie This solved an issue for me when standing up a `minikube` k8s cluster. Also, can I pretty please have write access to the repo via our org?
=> Add quay.io prefix to gfdatasource image

circle.yml
We're getting 404s when pushing & pulling from
hub.docker.io/weaveworks/gfdatasource. Just stop pushing/pulling there and use
only quay.io.
=> Stop pushing to Docker Hub

grafanalib/weave.py
We talked about this a little bit in the London office.
Justification is that when traffic switches from 200s to 500s, it's hard to tell how much overall traffic is being affected.
=> Stack Weave QPS graphs

grafanalib/weave.py
So we can use `QPSGraph` from gRPC services too.
=> Add gRPC status codes to QPSGraph

grafanalib/core.py
When you have no panel without defined span you'll get here division by zero exception
=> _balance_panels division by zero fixed

CHANGELOG.rst, grafanalib/core.py
=> SingleStat panel class added

CHANGELOG.rst, grafanalib/opentsdb.py
Opentsdb targets are different from Prometheus, here are classes for Opentsdb datasource.
=> OpenTSDB datasource targets added

grafanalib/core.py
Related to #26 
I wanted to do this with `attr.Attribute.convert`, but attr passes only field value to this callable, so there is no way to inspect other field values. 
On the other hand `attr.Attribute.validate` gets `instance`, `attribute`, and `value`. But setting field value in validation function is obscure.
So, I've just made an explicit method.
=> Issue26: Legend class field  should be set based on other values

CHANGELOG.rst, grafanalib/zabbix.py
Grafana Zabbix pluging support added.
Plugin docs: http://docs.grafana-zabbix.org/
=> Grafana Zabbix plugin support added

grafanalib/zabbix.py
I've noticed lint tests failing on zabbix.py
```
.env/bin/flake8 gfdatasource/gfdatasource grafanalib
grafanalib/zabbix.py:4:1: F403 'from grafanalib.validators import *' used; unable to detect undefined names
grafanalib/zabbix.py:161:61: F405 'is_interval' may be undefined, or defined from star imports: grafanalib.validators
grafanalib/zabbix.py:163:34: F405 'is_in' may be undefined, or defined from star imports: grafanalib.validators
grafanalib/zabbix.py:236:61: F405 'is_interval' may be undefined, or defined from star imports: grafanalib.validators
grafanalib/zabbix.py:238:34: F405 'is_in' may be undefined, or defined from star imports: grafanalib.validators
grafanalib/zabbix.py:275:61: F405 'is_interval' may be undefined, or defined from star imports: grafanalib.validators …
```
=> zabbix.py lint tests fixed

README.rst, grafanalib/core.py
This PR fixes three problems with the dashboard example in the README:
```
Traceback (most recent call last):
File "/usr/bin/generate-dashboard", line 9, in <module>
load_entry_point('grafanalib==0.1.2', 'console_scripts', 'generate-dashboard')()
File "/home/at/.local/lib/python3.5/site-packages/grafanalib/_gen.py", line 126, in generate_dashboard_script
run_script(generate_dashboard)
File "/home/at/.local/lib/python3.5/site-packages/grafanalib/_gen.py", line 116, in run_script
sys.exit(f(sys.argv[1:]))
File "/home/at/.local/lib/python3.5/site-packages/grafanalib/_gen.py", line 103, in generate_dashboard
dashboard = load_dashboard(opts.dashboard)
File "/home/at/.local/lib/python3.5/site-packages/grafanalib/_gen.py", line 24, in load_dashboard
module = SourceFileLoader("dashboard", …
```
=> Fix dashboard example in README

CHANGELOG.rst, grafanalib/core.py
- Introduce new `YAxes` type
- Introduce helper `single_y_axis` for common use case
- Add backwards compatibility for converting existing Y axes to new type
Fixes #2 
Fixes #42
=> Simplify Y axis specification

grafanalib/core.py
Allow to specify and display All value with templating.
```
:param allValue: specify a custom all value with regex,
globs or lucene syntax.
:param includeAll: Add a special All option whose value includes
all options.
```
=> template: Add grafana allValue and includeAll attribute in Template

grafanalib/prometheus.py
Related to #65 
Allow to use list of tuple or list of dict as expressions in PromGraph.
This allow to give specific parameters to target if needed, keeping
the possibility to stay on the simple tuple declaration.
=> prometheus.py: fix #65 PromGraph can now take tuple or dict as expressions

CHANGELOG.rst, grafanalib/weave.py
This change will require all callers of `QPSGraph` to supply their own name, but I think it's better.
=> Remove hard-coded data source name

grafanalib/core.py, grafanalib/tests/test_grafanalib.py
The `showTitle` option in `Row` is currently ignored and depends only on the `title` option.
=> Respect the `showTitle` option in `Row`

grafanalib/core.py
* Allows creation of dashboards which parametrise the input datasource [1]
Python code
```
...
dashboard = Dashboard(
inputs=[
DataSourceInput(
name="DS_PROMETHEUS",
type="datasource",
label="Prometheus",
pluginId="prometheus",
pluginName="Prometheus"
)],
...
```
Generated JSON
```
...
"__inputs": [
{
"description": "",
"label": "Prometheus",
"name": "DS_PROMETHEUS",
"pluginId": "prometheus",
"pluginName": "Prometheus",
"type": "datasource"
}
],
...
```
Python code
```
...
inputs=[
ConstantInput(
name="VAR_PREFIX",
label="prefix",
value="collectd"
),
...
```
Generated JSON
```
...
"__inputs": [
{
"description": "",
"label": "prefix",
"name": "VAR_PREFIX",
"type": "constant",
"value": "collectd"
},
...
```
[1] http://docs.grafana.org/reference/export_import/
=> Allow specifying a data source input

grafanalib/tests/test_grafanalib.py
Thanks for merging https://github.com/weaveworks/grafanalib/pull/80. Looking at the commits, I just realized that I broke the Circle CI tests. This should fix them.
=> Fix flake8 checks

grafanalib/core.py
A constant was missing to set the null point mode to null.
Add the constant NULL_AS_NULL for it.
=> core: add nullPointMode NULL_AS_NULL

grafanalib/core.py
Add a decimals attribute to the YAxis class.
It allows specifying the number of decimal places of the axis
description.
=> core: add decimals attribute to YAxis

grafanalib/core.py
The transparent attribute allows to make the background of the graph
transparent.
=> core: add transparent attribute to Graph class

grafanalib/core.py
Add the interval attribute to the Target class.
The attribute is called "Min step" in the grafana GUI.
The default value is an empty string, meaning grafana will determine the
interval.
=> core: add interval attribute to Target class

grafanalib/core.py
grafanalib required that a value for the label attribute of a Template
is set.
The grafana GUI does not require to set a label. If none is set, the
attributes value is null and the Name of the template variable is used
as label.
Use the same approach in grafanalib, set the default value to None.
The attribute needed to be moved down because of the following attrs exception:
ValueError: No mandatory attributes allowed after an attribute with a default
value or factory.  Attribute in question: Attribute(name='name',
[..]
=> templating: make setting label optional

grafanalib/core.py
Provide : http://docs.grafana.org/reference/templating/#value-groups-tags
Change the static `None` value to be part of the attribute list of `Template` class.
This commit provide `useTags`, `tagsQuery`, `tagValuesQuery` attribute on
`Template`
=> Templating: Allow to use groups/tags

circle.yml, grafanalib/_gen.py, grafanalib/tests/test_grafanalib.py, grafanalib/tests/test_opentsdb.py, grafanalib/tests/test_zabbix.py
Normally this commit adds python2 support for grafanalib which is
required to work with grafanalib right from `bazel`.
This commit replaces python3-only way of `importlib.machinery.SourceFileLoader` for dashboards with more generic `imp.load_source` available widely in python2 and python3.
This will help to create grafanalib rules for bazel to build dashboards right there without any strange behaviour of various python versions required for particular bazel rules and grafanalib. It will work simply on every python in fact without any impact to announced support for python 3.4 and 3.5.
Some links about bazel:
- https://www.bazel.build
- https://github.com/bazelbuild/rules_python
Some bazel rules like docker ones are written on python and running bazel with specified python version only …
=> Replace `SourceFileLoader` with python2 style `imp.load_source`

docs/example-elasticsearch.dashboard.py, grafanalib/elasticsearch.py
The PR adds partial support for creating graphs against an elasticsearch datasource.
It only adds support for basic query and aggregators.
Grafana supports more aggregators and query options that are not implemented yet.
=> Add support for Elasticsearch datasource #99

.gitignore, CHANGELOG.rst, Makefile, README.rst, circle.yml, tox.ini
Allows for testing multiple Pythons.
Builds on #107
=> Use 'tox' to run tests

.coveragerc, .gitignore, Makefile, tox.ini
Fail if our test coverage goes down.
Adjusts our CI so that we generate test coverage data and fail if it goes below 88%.
We really want 100% test coverage, but the first step is to ensure that it doesn't go lower. Test coverage is good because it catches bugs.
I'd like to do coveralls or something, but that's for later.
=> Generate test coverage report in CI

grafanalib/core.py, grafanalib/elasticsearch.py, grafanalib/zabbix.py
Fixes #105, preventing a class of unlikely by nasty bugs (see [Python gotchas](http://docs.python-guide.org/en/latest/writing/gotchas/#mutable-default-arguments))
Ensures that any default attribute values which are of mutable type are constructed with `attr.Factory`, to prevent accidental re-use.
If someone does mutate these values (not recommended) they will see weird and hard-to-predict behaviour.
=> Use attr.Factory for all "mutable" defaults

CHANGELOG.rst, grafanalib/core.py, grafanalib/tests/test_core.py
Updates a default in `SparkLine` to correctly return a colour, rather than try to call the colour.
Without this, you cannot construct `SparkLine` or `SingleStat`
Original fix is in #116, courtesy @xxr3376. This adds tests and changelog update.
=> Fix crasher bug in `SingleStat`

Makefile, gfdatasource/Dockerfile
Why? What?
- This should ultimately help for image-to-code back references.
- `org.label-schema.*` labels are now deprecated, in favour of `org.opencontainers.image.*` labels.
See also: https://github.com/opencontainers/image-spec/blob/master/annotations.md#back-compatibility-with-label-schema
- `MAINTAINER` is deprecated, in favour of the `maintainer` label.
- Git revision (`git rev-parse HEAD`) is now injected at `docker build` time.
Testing
```console
$ docker inspect quay.io/weaveworks/gfdatasource
[
{
[...]
"ContainerConfig": {
[...]
"Labels": {
"maintainer": "Weaveworks <help@weave.works>",
"org.opencontainers.image.revision": "c7bcf1cfa3f5b754afb27ae732efe576d9cca467",
"org.opencontainers.image.source": "https://github.com/weaveworks/grafanalib",
"org.opencontainers.image.title": …
```
=> Add org.opencontainers.image.* labels to Dockerfiles

grafanalib/core.py
The commits should be quite explicits (and small enough).
* `Target.expr` does nothing with Grafana 5.1.2, Graphite 1.1.3, `Target.target` works with the same syntax.
* `Graph` can be repeated too, adding support
* `Template.default` defaults to None for letting Grafana finding the best value
* `Template.dataSource`, `Graph.dataSource` default to None for using default DataSource
Fix a ~bug, support for repeating graphs, some sane defaults.
* `repeat`, `minSpan`: http://docs.grafana.org/reference/templating/#repeating-panels
Maybe fixing `Target.expr` isn't the right way to do it and we could do a dedicated `GraphiteTarget`, but as is wasn't already done, it went to `core.py`.
=> Add some defaults, add Target.target, Graph.minSpan, Graph.repeat

CHANGELOG.rst, grafanalib/prometheus.py
Fix the bug whereby all legends are missing from `PromGraph` panels.
The bug was caused by `legendFormat` moving from the 2nd to 3rd positional parameter of `Graph`.
So I just named all the parameters to avoid hitting this again.
=> Fix missing legends in PromGraph

CHANGELOG.rst, grafanalib/core.py
My use case for this is dashboards where the datasource is a templating
variable, thus needing to specify type in Template.
=> core: add type to Template

CHANGELOG.rst, grafanalib/core.py
Adds support like `DashboardLink` but for links to other URLs
for parity with the grafana editor
=> Add `ExternalLink` class for dashboard-level links to other pages

grafanalib/core.py
Allow to specify the refresh behavior of the template.
* On Dashboard Load
* On Time Range Change
Ref : http://docs.grafana.org/reference/templating/#query-options
>Controls when to update the variable option list (values in the dropdown). On Dashboard Load will slow down dashboard load as the variable query needs to be completed before dashboard can be initialized. Set this only to On Time Range Change if your variable options query contains a time range filter or is dependent on dashboard time range.
=> Template: add refresh arg.

grafanalib/core.py
Removes the magic values previously used, and makes this consistent with other params.
=> add named values for the Template.hide parameter

.circleci/config.yml, .gitignore, tox.ini
The JUNIT_XML setting was erroneously brought over from another repo; here we can just tell `tox` to put the results in a subdir and save that.
Hoping nobody is relying on the exact location of test results right now.
=> Save test results on CircleCI

.circleci/config.yml, grafanalib/weave.py
- Easier to pick out the large outlier values if you have many series
=> Set default sort order of "Weave" stacked-chart tooltips to DESC

CHANGELOG.rst, grafanalib/core.py
This parametr sets a grace period during which no notifications
are set.
In Grafana 6.X (probably 5.X too), ``for`` parameter for alert sets grace period during which Grafana does not send notifications about firing alert.
=> Add "for" param for alerts, Grafana 6.X

grafanalib/core.py
Adds support for setting the sort value of `Template`
The grafana UI supports these sort options, so hardcoding `1` makes grafanalib less complete.
=> support templating variable sort options

CHANGELOG.rst, grafanalib/core.py
Added 'diff', 'percent_diff' and 'count_non_null' as RTYPE for AlertConditions
It allows grafanalib to use those reducers in AlertConditions
These three RTYPEs were missing in core.py
=> Add 'diff', 'percent_diff' and 'count_non_null' as RTYPE

grafanalib/core.py, grafanalib/zabbix.py, setup.py
fixes method arguments that were deprecated in attrs, and removed intoday's attrs 19.2 release
builds are broken at master right now
=> pin to attrs 19.2 and fix deprecated arguments

.circleci/config.yml, Makefile, tox.ini
Currently CI is only running Python 2.7; it seems like a good idea to run it against the newest version in common with the CircleCI 1.0 config and also the newest version as of today.
I used `pyenv` to run the installs, since this is what the CircleCI 1.0 config did.
EDIT: the upstream build image is now installing Python 3, which requires a couple more changes.
=> Update versions of Python tested

grafanalib/_gen.py
Add two different versions depending on the Python version
Fixes #191
=> Fix up load_source() call which doesn't exist in Python 3.5

.github/workflows/publish-to-test-pypi.yml, CHANGELOG.rst
Following https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/ in order to make releases happen automatically (#56)
The first test ran against test.pypi.org: https://github.com/dholbach/grafanalib/runs/446202668
Please review and let me know if this generally makes sense.
=> Create release workflow definition

.github/workflows/publish-to-pypi.yml, CHANGELOG.rst, README.rst, docs/releasing.rst
- update release instructions with steps I used for 0.5.5
- fix typos in changelog
- add changelog entry for new release
- link to reopened grafanalib Slack channel
- mention 3.7 support on landing page
=> Update release instructions

.circleci/config.yml, CHANGELOG.rst, README.rst, tox.ini
Tests seem to be failing for python 2.7 - as [it has been EOL'ed](https://pythonclock.org/), drop the testing of it.
=> Drop test support for python 2.7.

grafanalib/core.py, grafanalib/tests/test_core.py
Provides proper support for custom template variables
Currently custom variables must be manually updated in dashboard settings after import. If you choose a variable in grafana you will see something like that:
After this PR it won't be needed. This was tested on grafana 5.1 and 5.2.
This feature respects custom defined options so if they were provided explicitly they will be preferably used. This allows to add some human-readable definition of values (see how it's done in test):
I'm not an expert in `attrs` and I put my logic in `__attrs_post_init__()`. I'm not sure if this is a proper place for such logic, please comment here.
I preserved backwards-compatibilty and still take `query` parameter as is. However it be constructed from options if they are provided: I'm not sure about this.
=> Add support for custom variables

.circleci/config.yml, .flake8, README.rst, docs/README.rst, docs/getting-started.rst, docs/index.rst, grafanalib/elasticsearch.py, grafanalib/tests/examples/example-elasticsearch.dashboard.py, grafanalib/tests/examples/example.dashboard.py, grafanalib/tests/test_examples.py, tox.ini
- Add python3.8 (current on Ubuntu 20.04) to tox and CircleCI
- decouple main github README from grafanalib docs RTD where we can use sphinx' "literalinclude"
- fix flake linter issues
- make examples run at all
- test examples as part of general tests
fixes: #55
=> Test examples automatically

Dockerfile.docs, docs/Makefile, docs/getting-started.rst, grafanalib/core.py
The log file said:
```
/home/docs/checkouts/readthedocs.org/user_builds/grafanalib/checkouts/latest/docs/getting-started.rst:21: WARNING: Include file '/home/docs/checkouts/readthedocs.org/user_builds/grafanalib/checkouts/latest/docs/example.dashboard.py' not found or reading it failed
```
so I
- added '-W' to docs build to make sure we get references right
- fixed the example reference and
- fixed some docstrings
=> Fix example showing up

CHANGELOG.rst, grafanalib/core.py
This changes the Table class's default ColumnStyle for "Time" to use upper case `T` instead of lower case `t` in its matching pattern. 
In my scenario at least, the Timeseries data I got back had its time column labeled as `time` not `Time` so the time formatting was not being applied. 
Is it universal that the data source will say capital T `Time` or does that vary? Should we cover both scenarios?
=> A lower-case `t` was preventing Table time column from formatting properly

CHANGELOG.rst, grafanalib/elasticsearch.py
This provides a bugfix to the Elasticsearch TermsGroupBy multi-bucket aggregator. This aggregator currently outputs a JSON field named order_by, whereas grafana uses the field name orderBy. This  commit updates grafanalib to match the required grafana JSON format.
This causes ordering in Elasticsearch term aggregation to function as intended.
This discrepancy can be seen by looking at the output JSON for the example Elasticsearch dashboard panels on the play.grafanalib.org site. There, the ordering output is placed under the orderBy field, rather than the order_by field. The effects of this become noticeable when using TermsGroupBy to plot Elasticsearch timeseries data, where the colouring/ouptut ordering will change every time a new Elasticsearch query is executed.
=> Bugfix for Elasticsearch TermsGroupBy ordering

CHANGELOG.rst, grafanalib/core.py
[`Threshold` values should be of the type float.](https://github.com/weaveworks/grafanalib/blob/master/grafanalib/core.py#L1676) The default `Thresholds` for `BarGauge` and `GaugePanel` cause a `TypeError` to be thrown when a custom `Threshold` isn't set because an integer is passed as the third argument to `Threshold` when a float is required.
I expected that `BarGauge` would render out-of-the-box if I provided the minimal required inputs as described by the docs: `title` and `targets`. Here is the setup that causes the `TypeError` mentioned above.
```python3
BarGauge(
max=500,
min=0,
span=6,
targets=[
Target(
target="highestAverage(aliasByNode(stats.timers.$page.api_calls.$device.$identity.$endpoints.median, 6), 10)"
)
],
title="This is some data"
),
```
Here is the error output from …
=> Update BarGauge and GaugePanel default Threshold values

grafanalib/elasticsearch.py
Apparently `attr.assoc` has been replaced by `attr.evolve` since a long time ago: https://www.attrs.org/en/stable/api.html#attr.assoc
closes: #224
Applying the PR and running `tox` won't show the warning mentioned in #224
=> Use attr.evolve instead of attr.assoc

tox.ini
Thanks Oriol Pauleria for the fix: https://github.com/weaveworks/grafanalib/pull/184/files#r349836896
closes: #223
After applying this and running `tox`, the error message in #223 does not appear any more.
=> Update to new junit_family

CHANGELOG.rst, grafanalib/elasticsearch.py
This adds support for the Elasticsearch bucket script pipeline aggregator
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-bucket-script-aggregation.html 
This is one of the core elasticsearch pipeline aggregations, and is natively supported by Grafana. 
It allows the user to combine the output of previous metric aggregations, using 
Elasticsearch Painless inline scripting.
Being able to apply scripts to the results of Elasticsearch metric aggregations can be very useful,
e.g. allowing one to plot the ratio of two sums over different document fields, as was my use case.
This includes id and hiding capabilities for the bucket script aggregator, as implemented elsewhere in #231
The Painless scripting docs are here: …
=> Add Elasticsearch bucket script aggregator

README.rst
Simple fix of the README:
Curl on linux by default output the content of the downloaded file on the STDOUT (you are maybe using MacOSX and I don't know curl's default behavior on MacOSX?). Add the `-o` option and the name of the file to create. Using `wget` maybe more portable?
Either there is an error in the README, or this would be more portable (between OSes).
=> Curl default behavior is to STDOUT content

CHANGELOG.rst, grafanalib/core.py
The SingleStat panel was deprecated in Grafana 7.0, Stat is thethe replacement for this.
The Stat panel uses a new mappings format so the classes StatMapping, StatValueMapping and StatRangeMapping were also added to support this.
Allows users to make use of the Stat panel in the latest version of Grafana
Closes #253 
The new mappings format is valid for not just the Stat panel, but didn't want to complicate this with the existing `Mapping` and `ValueMap` and `RangeMap` classes. Let me know if you think there is a better way to maintain backwards compatibility.
=> Add support for the Stat panel, which replaces SingleStat

MAINTAINERS
Add James Gibson as a maintainer
Hi, I work as a developer at BBC R&D where building a private cloud platform and using Grafanalib to define our dashboards as code to monitor our cloud platform.
=> Add James Gibson as maintainer

CHANGELOG.rst, grafanalib/core.py
Adds a 'transparent' setting to three panels that missed it (Heatmap, Piechart, Stat).
It was a missing setting, inconsistent with the rest of panels.
Nothing worthy of mention.
I didn't put the change for 'Stat' in the CHANGELOG.rst file as it is a new panel for this version.
=> Add transparency setting to Heatmap, Stat, PieChart panels

CHANGELOG.rst, grafanalib/core.py, grafanalib/tests/test_grafanalib.py
Adds a `#auto_ref_ids` method to Graph to add `refId` values for those `Target`s which do not have explicit `refId`s set, and preserves the IDs which are specified.  Its implementation is based on `Dashboard`'s `#auto_panel_ids` method.
It is requested in #128 and reduces toil for Dashboard creators and maintainers.
Any target list must have explicit `refId` attributes set today to make Grafana happy.  This is often an "auto-incrementing" alphabetical ID manually maintained by the creator of a dashboard.  This is only useful when one `Target` actually references another one - in other cases it is only toil.  I would like to reduce that toil.
None for now!
=> add `Graph#auto_ref_ids`

CHANGELOG.rst, grafanalib/core.py
As in the title, just adding of some data formats.
It makes the library more complete.
I needed it for my own implementation where I first define all types as objects, and then serialize them all. In the examples I saw that for at least the seriesOverride, a plain dictionary was used as well, but that didn't suit my use case (plus that it is not as self evident which fields are there).
I did not check the added types for completeness, so I might miss fields. Not sure if that's an issue at this stage.
=> Added more YAxis formats, added Threshold and SeriesOverride types

docs/CONTRIBUTING.rst, grafanalib/_gen.py, grafanalib/core.py, grafanalib/elasticsearch.py, grafanalib/influxdb.py, grafanalib/opentsdb.py, grafanalib/weave.py, grafanalib/zabbix.py
No functional change, have made quote style consistent across all files.
Triple Double quotes `"""` for docstrings
Double quotes `""` for human readable message or when string used for interpolation
Single quotes `''` for symbol like strings
Makes it easier for contributors to know the correct coding style to use as it is consistent throughout all files
=> Make quote coding style consistent

CHANGELOG.rst, grafanalib/core.py
We found out that on [Grafana 7.2.0-beta1](https://github.com/grafana/grafana/blob/master/CHANGELOG.md#720-beta1-2020-09-09) adds toggle to disable alert threshold visibility in graph panel was added. I would like `grafanalib` to support it.
This PR adds an option on the Graph class to be able to toggle that setting (`alertThreshold`).
To support this new flag on `grafanalib`.
Please check first title (What does this do). After checking how the json looked like on an instance of a graph using Grafana 7.3.0, decided to add the parameter that this PR describes to support the new attribute.
Didn't test on a real case. Just added the parameter and the serialization of the attribute.
Tests are passing locally.
No questions from my side.
=> Adding Alert Threshold flag to Graphs.

CHANGELOG.rst, grafanalib/core.py, grafanalib/tests/test_core.py
Extend the Stat panel with support for repetitions.
I am using Stat panels in overview dashboards. Stat panels should be repeated according to the content of a variable (in my case the variable contains all tags from a certain measurement).
Without this little change, I had to generate the dashboard and either amend the missing repetitions by jq or later add them manually in Grafana. My intention is to generate the entire Grafana content completely automated.
=> Add support for repetition to the Stat panel

tox.ini
Removes deprecation warning from pytest
=> Use pytest --strict-marker over --strict

CHANGELOG.rst, grafanalib/humio.py, grafanalib/tests/test_humio.py
Humio is available as a plugin datasource, documented [here](https://grafana.com/grafana/plugins/humio-datasource/).
The Humio query language is documented [here](https://docs.humio.com/reference/language-syntax/). 
Adding support for Humio queries in grafanalib.
Humio is offered as a plugin datasource in Grafana, and adding this will allow people to create graphs with Humio data. 
Humio is a log aggregation, storage, and analysis tool similar to Elasticsearch. It is available as both as self-hosted or as a SaaS product.
=> Adding humio datasource. 

CHANGELOG.rst, grafanalib/core.py, grafanalib/elasticsearch.py
AlertCondition should contain the ElasticsearchTarget but since ElasticsearchTarget doesn't inherit from Target you get a validator the error
Closes  #322
=> Add elasticsearch alert condition override

grafanalib/core.py
Repeat is an object so isn't json serializable this change will add the necessary fields to the pannel object so that we can create repeat panels. 
This is a bug fix. 
Tested locally and was able to create repeated panels.
=> Fix Repeat for Panel

CHANGELOG.rst, grafanalib/core.py
Changes the default for target datasource
The generated dashboard now works with newer versions of Grafana.
See:
https://github.com/weaveworks/grafanalib/issues/340
=> Set target datasource as None instead of empty string

CHANGELOG.rst, grafanalib/core.py
This PR removes the maxDataPoints field from multiple panels b/c it's inherited from Panel.
=> Remove re-defined maxDataPoints from multiple panels

CHANGELOG.rst, grafanalib/cloudwatch.py
This PR adds 'hide' parameter to CloudwatchMetricsTarget class
hide parameter is useful when you need to use a metric, but you don't want to display it. 
Note that 'hide' parameter is already defined for the `Target` class.
Example:
```
Graph(
targets=[
CloudwatchMetricsTarget(
metricName="SignInSuccesses",
namespace="AWS/Cognito",
alias="OK",
id="ok"
),
CloudwatchMetricsTarget(
metricName="SignInSuccesses",
namespace="AWS/Cognito",
id="total",
hide=True,
),
CloudwatchMetricsTarget(
id="failed",
expression="SUM([total, -ok])"
),
],
),
],
```
=> Added 'hide' parameter to CloudwatchMetricsTarget class

CHANGELOG.rst, grafanalib/core.py
* Accept 'CloudwatchMetricsTarget' as target for 'AlertCondition'
This PR changes 'target' attribute validator in AlertNotifications class
I've encountered an issue where 'AlertNotifcation' class didn't accept CloudwatchMetricsTarget as target
I've been considering creation of zope.interface.Interface and veryfing based on attrs.validators.provides, but this simple solution seems to be good enoguh for me
=> Change 'target' attribute validator to a generic one in 'AlertCondition'

CHANGELOG.rst, grafanalib/core.py, grafanalib/tests/test_core.py
Move the alertRuleTags field from Graph to Alert.
Because the dashboard extracts the alertRuleTags field from an alert mapping.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/grafanalib/360)
=> Move alertRuleTag from Graph to Alert.

CHANGELOG.rst, grafanalib/core.py, grafanalib/tests/test_core.py
It's pretty straightforward code, which allows to add transformations (https://grafana.com/docs/grafana/next/panels/transformations/types-options/#transformation-types-and-options) for the Table panel. At the current moment, it just translate list of dicts with transformations to JSON as-is.
I really miss this feature for the Tables. Adding transformations to the tables is very common pattern, which allows to increase readability and usability of Tables.
=> Add transformations field for the Panel class

CHANGELOG.rst, grafanalib/core.py, grafanalib/tests/test_core.py
This adds a new attribute called `extraJson` to the `Panel` class, enabling users to add attributes that are not currently supported by grafanalib, for example `fillGradient` and color mappings:
Example 1, a Graph with aligned y-axes and a fill gradient:
```py
Graph(
title="...",
dataSource=datasource,
yAxes=YAxes(
left=YAxis(format="bytes", min=None),
right=YAxis(format="none", min=None),
),
targets=[
],
extraJson={
"yaxis": {"align": True},
"fillGradient": 6
}
)
```
Example 2, a pie chart with combining enabled and percentage shown in the legend:
```py
PieChart(
title="..",
dataSource=datasource,
targets=[
],
pieType="donut",
extraJson={
"legend": {"percentage": True},
"combine": {"label": "Others", "threshold": "0.01"}
}
)
```
Other nice uses is for gradient color mappings:
- For …
=> Add extraJson attribute to the Panel class for overriding the panel with raw JSON

CHANGELOG.rst, grafanalib/elasticsearch.py
This adds support for inline scripts to Elasticsearch metrics.
Allows users to apply calculations to metrics directly
We have some metrics stored as Bytes/s but want to show them as bits/s, this patch allows the setting of inline to allows the calculation to be performed. 
With this patch, if inline is set then the output json looks something like 
`
{  
"field": "port_1_bytes",
"hide": false,
"id": "4", 
"inlineScript": "_value*8",
"meta": {}, 
"settings": {  
"script": { 
"inline": "_value*8"
}
},
"type": "max"
},        
`
If inline isn't set then we use:
`
{  
"field": "port_1_bytes",
"hide": false,
"id": "4", 
"inlineScript": "_value*8",
"meta": {}, 
"settings": {},
"type": "max"
},        
`
There is one additional change here, I found that for DateHistogramGroupBy, I had too add …
=> Add inline script support for Elasticsearch metrics

grafanalib/core.py
Setting 0 as default min value for yAxes is arbitrary and messes up all of Grafana's auto-scaling features. This commit sets the default to None and lets Grafana choose the min value.
=> Do not default to 0 for min value for yAxes

CHANGELOG.rst, grafanalib/core.py
For the Template class, when the template type is interval is selected, the auto properties are missing.
=> Added missing auto interval properties in Template

CHANGELOG.rst, grafanalib/cloudwatch.py, grafanalib/tests/test_cloudwatch.py
Introduces the [Cloudwatch Logs Insights Target](https://grafana.com/docs/grafana/latest/datasources/aws-cloudwatch/#using-the-logs-query-editor)
We can visualise both Cloudwatch metrics and logs within the same dashboard
=> Add Cloudwatch Logs Insights Target

grafanalib/core.py, grafanalib/tests/test_core.py
This PR adds the missing attributes to timeseries visualization
This allows the grafanalib users to override series in Timeseries visualization
=> Add missing overrides to timeseries visualization

CHANGELOG.rst, grafanalib/core.py, grafanalib/tests/examples/example.dashboard-with-sql.py, grafanalib/tests/test_core.py, setup.py
This change is supposed to make it possible to define SQL queries as well for targets so Data Sources like MySQL, PostgreSQL can work too.
Creates a New Target class named SqlTarget. With this now it is possible to define panels (Graphs) with SQL queries in them for datasources like MySQL and PostgreSQL.
SQL based datasources are really widespread and with this addition now those panels can also be defined by grafanalib.
It was already mentioned in a feature request.  Feature Request: support sql queries #153 
No questions from my side.
=> Add SQL Target

CHANGELOG.rst, grafanalib/core.py, grafanalib/tests/test_core.py
Fixes the TextPanel class.
Makes it work again with Grafana 8.
Could you check if that works with other Grafana versions? The original did not wirk with 8, but I dont know if the fixed one works with <8.
=> Fix text panel

CHANGELOG.rst, grafanalib/cloudwatch.py
Adds the ability to set datasource for CloudWatch targets, like in regular `Target`.
So that CloudWatch metrics could be used in panels with mixed datasources.
=> Datasource parameter for CloudWatch targets

CHANGELOG.rst, grafanalib/core.py
Adds the ability to filter alerts in AlertList panel.
Because filtering doesn't work right now.
Not sure if it is because of recent Grafana version, or using new grafana alerting system, but `AlertList` panels created manually have quite different model from the ones generated by grafanalib, and not all parameters work for it.
I don't know what is the correct course of action would be here, but for now I've just fixed one parameter that I need (hopefully in a non-breaking way).
=> alertName parameter for AlertList panel

CHANGELOG.rst, grafanalib/core.py
Adds the ability to set thresholdsStyleMode in TimeSeries panel.
Because the threshold drawing style could not be set.
In the TimeSeries panel, the threshold drawing style could not be set.
=> Add thresholdsStyleMode parameter for TimeSeries panel

CHANGELOG.rst, grafanalib/core.py
It adds a new parameter `legendCalcs` to the TimeSeries panel to define which calculations are shown in the legend. 
We were missing this feature duration the creation of out dashboards and think other user would also like to use it.
Only introduces the new parameter, no big thing ;)
None
=> Add support to set legend values on TimeSeries

CHANGELOG.rst, grafanalib/influxdb.py
Under each InfluxdbTarget, a different data source can be specified. This allow the merging of trends from different influxb into the same Panel. This is done by adding the 'datasource' parameter to the InfluxdbTarget object
Add a datasource for different InfluxdbTarget. Without this option, the InfluxdbTarget could only have one default datasource specify outside Target.
Different datasource for each Influxdbtarget allows the merging of different trend onto the same Panel.
The current setup using dataSource specify outside the target stencils. Adding a data source within the target allows a combination of different data sources on the same panel. This is carried out via adding "datasource" parameter within the influxdbTarget object similar to adding the parameters like query and …
=> add 'datasource' parameter for InfluxdbTarget

README.rst
- We support up to python 3.10
- Meetings were put on halt
- Update on grafanalib maintenance
Signed-off-by: Daniel Holbach <daniel@weave.works>
=> Update documentation regarding development

grafanalib/core.py
Adds support for the 3rd type of graph tooltip at the dashboard level.
This is a fairly common option, and closes an open issue.
Is there a plan for managing the ever evolving schema?  I can't find where particular `schemaVersion` values are defined in Grafana, but note that the default value is in this repo is 12, whereas the current value for 8.5.2 is 36.  Looking at Grafana code, it appears that they may be changing how the schema stuff is handled (comments hinting that this field is the old way, and 36 is a "handoff" version to something else).
I realize we can't just bump the default schema without breaking users of older Grafana builds (but maybe the 12 can be bumped if that can be tied to a specific Grafana version?  Whatever version introduced 12 probably isn't supported anymore.) …
=> Add support for Shared Tooltip on graphs (fixes #476)

grafanalib/core.py, grafanalib/tests/test_core.py
Target validation requires that refId is not blank. This is because an AlertCondition needs to apply to a target refId.
However, the current validation does not work if the refId is omitted. This is because it is defaulted to "" if it's missing, but the previous check was just for `hasattr`.
It prevents people making invalid alerts that do not apply to any target. This could be a source of bugs.
=> fix: target validation

grafanalib/core.py, grafanalib/tests/test_core.py
There are a couple of mistakes in the Grafana 9 Alerts-As-Code `AlertRulev9` JSON output.
Firstly, the absence of `grafana_alert` means that uploading the output JSON fails with a validation error: `{"message":"unexpected backend type (grafana) for payload type (lotex)","traceID":""}`, which specifically is [this error in Grafana](https://github.com/grafana/grafana/blob/718620c197614f94dd15231790fc6530c3cc8b8a/pkg/services/ngalert/api/errors.go#L20-L25).
Secondly, the fields `noDataState` and `execErrState` were renamed to `no_data_state` and `exec_err_state` in v9, meaning these settings were not applied correctly.
With these changes my alerts upload successfully and appear to be correct, but if I spot further mistakes I'll make follow-up PRs.
=> fix: AlertRulev9 JSON schema is not correct

grafanalib/cloudwatch.py
Add support for `statistic` field in `CloudwatchMetricsTarget`
The existing `statistics` field is being ignored by grafana 9.x, it must be named `statistic` (not `statistics`) and must be a string (not a list)
=> Add support for `statistic` field in `CloudwatchMetricsTarget`

CHANGELOG.rst, grafanalib/core.py, grafanalib/tests/test_core.py
Add support for [Bar chart panel](https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/bar-chart/).
Add support for a new, useful panel type.
The panel allows you to graph categorical data. It supports only one data frame, and it must have at least one string field that will be used as the category for an X or Y axis and one or more numerical fields.
Closes #510
=> Add support for Bar chart panel

grafanalib/core.py
The Now delay can be applied to a dashboard (via a TimePicker), which will delay the time at which `now` applies when looking at data on a dashboard.
This was missing from Grafanalib.
=> Expose Now delay option in TimePicker

CHANGELOG.rst, grafanalib/core.py, grafanalib/tests/examples/sqltarget_example_files/example.sql, grafanalib/tests/examples/sqltarget_example_files/example_with_params.sql, grafanalib/tests/test_core.py
Add the ability to parse SQL queries from files.
Parsing files instead of using query strings reduces code length and improves code readability.
Complex panels and dashboards use multiple long queries. Parsing them from files shortens the code length and leads to a more readable and maintainable codebase. The implementation supports parametrizing the queries with dictionary as an attribute to help writing queries with variables.
=> Update SqlTarget to support parsing queries from files

grafanalib/cloudwatch.py, grafanalib/core.py, grafanalib/tests/test_core.py
Some small fixes for Grafana 9 alerts support:
- Grafana9 AlertExpression accepts only Targets while CloudwatchMetricsTarget for some reason is not a Target
- AlertCondition can include multiple conditions, each with its own target
- Maintain support for CloudwatchMetricsTarget in alerts
- Support the full complexity of the implementation of the new alert
=> fix: AlertRulev9 does not support CloudwatchMetricsTarget

grafanalib/elasticsearch.py
This adds support for the "Rate Aggregation" as a metric in an Elasticsearch query.
This is supported in Grafana, and my team needed it for something. I figure others might too.
=> Add support for Elasticsearch Rate Metric Aggregator

CHANGELOG.rst, grafanalib/core.py, grafanalib/tests/test_core.py
Add ``useNewAlerts`` property to ``AlertCondition`` and default it to ``False``
When ``AlertCondition`` is used inside of ``Alert.alertConditions``, json serialization fails as the property is not set. When the default is set to ``False`` this will allow the ``AlertCondition`` to behave as expected when used with old grafana alerting. In case of 8.x and 9.x, this is already overriden to ``True`` in the code so the functionality will work as expected in the new alerting.
```py
In [14]: from grafanalib import core as G
In [15]: from grafanalib import _gen as glGen
In [16]: import json
In [17]: json.dumps(G.Alert(name='name', message='message', alertConditions=[G.AlertCondition(G.Target(refI
...: d="A"), G.Evaluator('a', 'b'), G.TimeRange('5', '6'), 'd', 'e')]), cls=glGen.DashboardEncoder) …
```
=> Fix AlertCondition backwards compatibility

CHANGELOG.rst, grafanalib/elasticsearch.py, grafanalib/tests/test_elasticsearch.py
Adds a file for unit tests on the elasticsearch module
Adds a unit test for the RateMetricAgg class added in #583 
Unit tests are a good thing. I found a missing parameter implementation when making this (the fix for that is also part of this PR)
https://github.com/weaveworks/grafanalib/issues/589
=> Add unit test for RateMetricAgg in elasticsearch

grafanalib/core.py
Currently Stat(panel) doesn't support color option, so it still always be grey color when using Stat(panel)
Have a choice of color improve the readable of panel
Color option is simpler than thresholds, in the case of no need to define thresholds
not sure about the combination, in my case, I always use together with colorMode="background" and graphMode="none"
=> Add color support in Stat(panel)

CHANGELOG.rst, grafanalib/core.py, grafanalib/elasticsearch.py
- Added a units parameter to core.Table.
- Added a hide flag to ElasticsearchTarget.
- Allows to display table entries as units of time/bytes/anything else.
- ElasticsearchTarget is responsible for query results, so it is essential to be able to choose which ones to display with composite queries. For example if we want to display the ratio between two sums but not to see the sums.
=> add unit to tables and hide flag to es targets

README.rst
Update max python version compatibility in readme to include python 3.11. 
3.11 is part of tests so README should not mislead about only supporting up to python 3.10
See passing tests https://github.com/weaveworks/grafanalib/actions/runs/5575606128/job/15097310698. It is also published to pypi.
I don't think such a minor docs fix needs a CHANGELOG entry, correct?
=> Update python compatibility in README

CHANGELOG.rst, grafanalib/azuredataexplorer.py, grafanalib/tests/test_azuredataexplorer.py
Add support for Azure Data Explorer queries in grafanalib
Azure Data Explorer is [offered as a plugin datasource in Grafana](https://grafana.com/grafana/plugins/grafana-azure-data-explorer-datasource/) and adding this will let people create graphs based on data from Azure Data Explorer.
[Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/) is a log analytics cloud platform optimized for ad-hoc big data queries.
=> Added support for Azure Data Explorer datasource plugin

CHANGELOG.rst, grafanalib/core.py
This change allows sorting table rows by their fields
This is a useful feature which is supported in grafana v8:
https://grafana.com/docs/grafana/v8.0/panels/visualizations/table/#sort-column
`sortBy` in grafana's Table panel options:
https://github.com/grafana/grafana/blob/v8.0.x/public/app/plugins/panel/table/models.gen.ts#L17
The name for `TableSortByField` was inspired by the matching type in grafana:
https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Table/types.ts#L24
=> Added sortBy parameter to Table panel

CHANGELOG.rst, grafanalib/core.py, grafanalib/tests/test_core.py
Extends the implementation of DashboardLink to support creating both direct links and lists of dashboards.
This enables grafanalib users to fully employ the DashboardLink feature. The previous JSON model was no longer accurate for recent grafana versions, meaning dashboard links were not properly generated. Here we add all available fields, allowing users to create dashboard links correctly from grafanalib.
Dashboard Links are a way to create links along the top of a dashboard, linking either to other sets of dashboards from the same organization or arbitrary external resources. See the documentation here: https://grafana.com/docs/grafana/latest/dashboards/build-dashboards/manage-dashboard-links/#manage-dashboard-links
I have removed a parameter from the old DashboardLink class, …
=> Main improved dashboard links

CHANGELOG.rst, grafanalib/core.py
Added ``tooltipSort`` parameter to TimeSeries panel
This option was missing for the tooltips in TimeSeries panel
Added ``tooltipSort`` parameter to TimeSeries panel
n/a
=> added tooltipSort to TimeSeries Panel

CHANGELOG.rst, grafanalib/core.py, grafanalib/tests/test_core.py
Set default Heatmap options to an empty list instead of null.
Older versions of Grafana (e.g. v10.2) fail on empty Heatmap options (for newer version this is already fixed in Grafana https://github.com/grafana/grafana/pull/79083)
=> Heatmap default options

CHANGELOG.rst, grafanalib/core.py
Extends the list of accepted orientations in BarGauge to include auto: https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/bar-gauge/#orientation
This allows grafanalib's range to cover a more complete set of valid grafana configurations.
https://github.com/weaveworks/grafanalib/issues/634
=> Add 'auto' to the list of accepted orientations for BarGauge.

CHANGELOG.rst, grafanalib/core.py
This change enables you to configure value mappings for Table. Previously, the `mappings` argument provided would just get ignored.
I am not sure about backwards compatibility, but I am using Grafana v9.4.7 and it expects `mappings` in this location.
=> add mappings to field config for Table

CHANGELOG.rst, grafanalib/formatunits.py
This PR corrects the spelling errors for temperature units in `formatunits.py`:
- `CELSUIS` to `CELSIUS`
- `FARENHEIT` to `FAHRENHEIT`
- This a breaking change. Anything specific to handle it?
=> fix: correct spelling errors for temperature units

.github/workflows/check-sphinx-and-links.yml, CHANGELOG.rst, grafanalib/core.py
Added `neutral` option for `GaugePanel` (supported by Grafana 9.3.0 
- https://github.com/grafana/grafana/discussions/38273)
Why it's good idea is described in the grafana discussion https://github.com/grafana/grafana/discussions/38273.  In this commit just add it as option to set.
=> Neutral option for GaugePanel

CHANGELOG.rst, grafanalib/core.py
Some targets (Influx for example) use `alias` instead of `legendFormat` (which is Prometheus "alias"). This commit setup both of them by current `legendFormat`.
For Influxdb `SqlTarget` isn't now possible to set "alias" via `Target`. Of course is possible to use `InfluxDBTarget` (https://github.com/weaveworks/grafanalib/blob/main/grafanalib/influxdb.py) but there missing other options (like `hide`, because it's not child of `Target`). So I've chosen solution to extend `Target` to support all needed for my influx.
If you don't like this solution, I see other solutions
1. add new `alias` option - similar as #285 
2. InfluxDBTarget class should be inherit from `Target`
=> Target alias

CHANGELOG.rst, grafanalib/cloudwatch.py
To generate certain dashboards with the Cloudwatch datasource, specify the queryMode
Fix a simple issue
For many queries I need this option
=> cloudwatch: add queryMode attribute

grafanalib/core.py
As discussed in https://github.com/grafana/grafana/issues/50855#issuecomment-1183431665, panels of rows with collapsed=False should be added to the list of panels that contains that row.
Adding non-row panels makes auto_panel_ids() fail with
```
File ".../grafanalib/core.py", line 1751, in auto_panel_ids
ids = set([panel.id for panel in self._iter_panels() if panel.id])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ".../grafanalib/core.py", line 1731, in _iter_panels
for row_panel in panel._iter_panels():
^^^^^^^^^^^^^^^^^^
AttributeError: 'TimeSeries' object has no attribute '_iter_panels'
```
This change fixes this exception.
=> Allow using non-row panels in dashboard's panels
