weaveworks/grafanalib

Makefile
gfdatasource/gfdatasource

Lint gfdatasource

---

README.rst
grafanalib/core.py

This is @astronaut1712's work from #10, followed up with a single commit (ec67b9e) where I apply some review feedback directly in order to save another roundtrip.

Support Alert configuration in graph for Grafana 4.x

---

.gitignore
Makefile
circle.yml
grafanalib/_gen.py
grafanalib/core.py
grafanalib/tests/test_grafanalib.py
grafanalib/weave.py
setup.py

I started this work a couple of weeks ago before I went on leave, and then dug it up on my tube journey in. 
No behavioural changes here, but sets us up so that we can get rid of the `next(GRAPH_ID)` nonsense. Also adds tests, which are pretty important for Python projects.

Objects not functions

---

grafanalib/core.py

Fixes typo / auto-complete bug introduced by #17

Default renderer not default refresh

---

grafanalib/core.py

Legend class additional fields

Legend class additional fields

---

CHANGELOG.rst
grafanalib/core.py

Xaxis class update.
`mode`, `name`, `values` fields added.

XAxis class update: additional fields

---

CHANGELOG.rst
grafanalib/core.py
grafanalib/tests/test_grafanalib.py
grafanalib/weave.py

Method for autogenerating IDs

---

grafanalib/opentsdb.py
grafanalib/tests/test_opentsdb.py
grafanalib/tests/test_validators.py
grafanalib/tests/test_zabbix.py
grafanalib/validators.py
grafanalib/zabbix.py

Hi, I want to move all custom validators into dedicated file

Custom validators moved to dedicated file. Tests for custom validator.

---

CHANGELOG.rst
grafanalib/core.py
grafanalib/tests/test_validators.py
grafanalib/tests/test_zabbix.py
grafanalib/validators.py
grafanalib/zabbix.py

Grafana Zabbix triggers panel.
http://docs.grafana-zabbix.org/reference/panel-triggers/ (page exists but its blank =))

Zabbix Triggers panel added

---

README.rst
gfdatasource/gfdatasource
grafanalib/core.py

Add app initialisation options to gfdatasource

---

CHANGELOG.rst
grafanalib/prometheus.py
grafanalib/weave.py

Moves it out of weave module.
Fixes #8

Move PromGraph to prometheus module

---

grafanalib/core.py

Found [here](https://github.com/grafana/grafana/blob/2fc67da69aab515968d009335389941fbacbb340/public/app/core/utils/kbn.js#L418-L419)

Add bps and Bps formats

---

.gitignore
README.rst

Add a _developing_ section to the README, showing how to build from source. Fixes #70

Document how to build the project from source

---

README.rst

Remove unused import from example in README.

Remove unused import

---

grafanalib/core.py

Hello!
Just added 3 options to the core:
Repeat to Row: Allows you to repeat rows for each value in variable
Regex to Templating: Allows you to filter your values
Multi-Valued to Templating: Allows you to use multi-valued variables

Repeat, Multi-Value and Regex options added

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
docs/CODE_OF_CONDUCT.rst
docs/CONTRIBUTING.rst

Three purposes:
- help contributors
- help me review better
- maybe enable other people to help with maintenance

Contribution guidelines

---

grafanalib/core.py

timeFrom: time range that Override relative time

timeFrom: time range that Override relative time

---

CHANGELOG.rst
grafanalib/core.py

To support instant property in target settings.
We need this property in our project, and I believe others need it too.

Support instant attribute in Target.

---

CHANGELOG.rst
README.rst

add information about how to get help to the bottom of `README.rst`

add information about how to get help

---

gfdatasource/Dockerfile

A small tweak to the Dockerfile!

Avoid caching alpine indexes and downloads

---

CHANGELOG.rst
grafanalib/core.py

Add sorting attributes to Legend

---

CHANGELOG.rst
grafanalib/core.py

(This is a trivial, straight-forward fix.)

allow time overrides for tables

---

grafanalib/core.py

Adds support for OK state in alerts
allows users to treat alerts that havbe no data as ok
issue #154

close #154 add ok for alert state

---

grafanalib/elasticsearch.py

allows you to filter for cardinality metric when search elastic search
more ability for users to query elastic

add cardinality metric aggregator for elastic search

---

README.rst
docs/example-elasticsearch.dashboard.py
docs/example.dashboard.py
grafanalib/_gen.py
grafanalib/core.py
grafanalib/tests/test_grafanalib.py
grafanalib/tests/test_opentsdb.py
grafanalib/tests/test_validators.py
grafanalib/tests/test_zabbix.py
grafanalib/weave.py
grafanalib/zabbix.py

This PR makes some small changes in order to pass the test suite.
It doesn't change "anything" only some deprecation/errors during tests.
I think that it's clear to have different changes in splited commits to review the PR so Before merge it will be necessary to squash all the commits.

Repair tests

---

gfdatasource/Dockerfile

bump dockerfile to alpine 3.10 as base 

---

CHANGELOG.rst
README.rst

Fix the example in README.rst to make it correctly generate dashboard JSON file.

Fix example in README

---

MAINTAINERS

Welcome @matthewmrichter who has agreed to become a maintainer of this project.

Add Matt Richter as maintainer

---

CHANGELOG.rst
setup.py

I updated setup.py and the release changelog. Together with #201 we can see if this process works.
Might be worth releasing this on Monday instead? :-) (I'll be off on a :steam_locomotive: in a bit.)

release 0.5.5

---

CHANGELOG.rst
grafanalib/core.py

Adds the ability to create guage panels in grafana 6 and up
ability to take full advantage of grafana's built-in panels

add guage panel

---

CHANGELOG.rst
grafanalib/core.py

Adds the ability to create bar guage panels in grafana 6 and up
ability to take full advantage of grafana's built-in panels

Add bar guage panel

---

CHANGELOG.rst
grafanalib/core.py

Reverts weaveworks/grafanalib#179 - some small changes to make here to pass circleci testing

Revert "Add bar guage panel"

---

CHANGELOG.rst
grafanalib/core.py

Reverts weaveworks/grafanalib#205 - Will apply circlci fixes to this.
Sorry for the PR spam here. I just wanted to revert to make sure I didn't hose anybody else up.

Revert "Revert "Add bar guage panel""

---

grafanalib/core.py

Add description attribute to Dashboard. Thus description field can be filled for dasboards.
Descriptions (and comments) are always a good idea. ;-) Other classes also have a description field in grafanalib.

Add description attribute to Dashboard.

---

README.rst
setup.py

Add another link to docs in help section

---

CHANGELOG.rst
README.rst
docs/getting-started.rst

Fix link in main README, update changelog, mention python 3.8.

Small docs fixes.

---

CHANGELOG.rst
grafanalib/elasticsearch.py

allows you to filter for Average metric when search elastic search
more ability for users to query elastic

add average metric aggregation for elastic search

---

.github/workflows/check-sphinx-and-links.yml

stop checking http://sphinx-doc.org/ - the link is part of the theme and it times out right now

stop checking http://sphinx-doc.org/

---

grafanalib/elasticsearch.py

This adds in missing defaults in for aggregation IDs and aggregation hiding.
This is a bugfix for #245, caused by #235.

Fixed up ID and hiding for Average Terms aggregation

---

grafanalib/core.py

Remove links to singlestat for now, so we can continue to land changes.

---

grafanalib/core.py

Readd links to singlestat docs (now Stat)

---

CHANGELOG.rst
grafanalib/core.py

Add SVG class for the SVG panel
Allows people to use the SVG panel plugin 
https://grafana.com/grafana/plugins/marcuscalidus-svg-panel

Add SVG class for the SVG panel

---

README.rst

Update community meeting link to Google Meet

---

CHANGELOG.rst
grafanalib/core.py

Adds support for Pie Chart panels
https://grafana.com/grafana/plugins/grafana-piechart-panel
How members to add pie chart to Grafana

Add PieChart class for creating Pie Chart panels

---

grafanalib/core.py
grafanalib/influxdb.py

The pipeline's linter was complaining about formatting because we lost a few blank lines.

A few blank lines as requested by the linter.

---

CHANGELOG.rst
docs/getting-started.rst
setup.py

Prep changelog for 0.5.8 release.

add missing bits, sumarise release, thank James

---

README.rst

Moving date, moving back to Zoom.

update meeting information

---

CHANGELOG.rst
grafanalib/core.py
grafanalib/formatunits.py

Adds constants for all the Grafana value formats (https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/valueFormats/categories.ts)
Easy to template the correct formatting required

Add constants for all Grafana value formats

---

.github/dependabot.yml

Move to weekly dependency check.

Move to weekly dependency check

---

CHANGELOG.rst
grafanalib/core.py

Add hide parameter to Target
It's useful for cases where panel has few queries - one for displaying data and another one with hide=True - is used for Alerts

add hide parameter to Target

---

grafanalib/core.py

Add missing attr.s decorator to SeriesOverride

---

CHANGELOG.rst
grafanalib/core.py

Ensures all query panels have the same default query settings
Based on PR #177
Makes all panels consistent

Create panel object for all panels to inherit 

---

CHANGELOG.rst
grafanalib/core.py
grafanalib/tests/test_core.py

Adds support for dashboard list panel type
Closes #216

Add support for dashboard list panel

---

grafanalib/core.py

Add validator to dashboard list arguments

---

CHANGELOG.rst
setup.py

Prepare 0.5.9 release

---

CHANGELOG.rst
grafanalib/core.py
grafanalib/tests/test_core.py

Add logs panel

---

CHANGELOG.rst
grafanalib/core.py
grafanalib/weave.py

Remove deprecaterd attr.assoc

---

CHANGELOG.rst
grafanalib/core.py

Add option to hide dashboard time picker
closes #260

Add option to hide dashboard time picker

---

CHANGELOG.rst
grafanalib/core.py
grafanalib/tests/examples/example.dashboard.py
grafanalib/tests/test_core.py

Add `Notification` class
It will allow to set up and configure `notifications` on `Alert`

add Notification class

---

CHANGELOG.rst
grafanalib/core.py

Add alertRuleTags field to graph panel
closes #316

Add alertRuleTags field to graph panel

---

docs/getting-started.rst

Add note to docs about supported grafana versions so it is clear to users what grafana version they can use with grafanalib
Closes #176

Add note to docs about supported grafana versions

---

.github/workflows/check-sphinx-and-links.yml

Switch to lychee-action
Closes #312

Switch to lychee-action for link checking

---

.flake8
CHANGELOG.rst
grafanalib/core.py
grafanalib/tests/examples/example.dashboard.py
grafanalib/tests/test_grafanalib.py

And support for creating dashboards using gridPos while maintaining backwards compatibility with original Row method used. 
This PR does not add all the new features of the newest Grafana schema versions, these can be added in separate PR's
Based off #172 - had to start a new PR as master branch has diverged too far from PR to make a rebase practical
Closes #250 
Closes #139

Add support for gridpos

---

CHANGELOG.rst
grafanalib/core.py
grafanalib/tests/test_core.py

Add support for thresholds to graph panels
This code has not been tested if the thresholds created work in practice, but follows the same pattern as other panels
Closes #171

Add support for thresholds to graph panels

---

grafanalib/core.py
grafanalib/zabbix.py
setup.py

Based off #309, new PR due to inactivity

Enable use with pre-17.4.0 versions of attr

---

CHANGELOG.rst
setup.py

Prep for 0.5.10 release

---

CHANGELOG.rst
grafanalib/core.py

Add nameFilter field for the AlertList panel.
Enable to filter alerts by their name in an AlertList panel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/grafanalib/338)

Add nameFilter field for the AlertList panel.

---

CHANGELOG.rst
grafanalib/_gen.py
grafanalib/core.py

bugfix load_module for python version 2.x, 3.4 and 3.5

---

CHANGELOG.rst
grafanalib/tests/examples/table-example-dashboard.py
grafanalib/tests/examples/table-example.dashboard.py
grafanalib/tests/examples/upload_grafana_dashboard.sh

Shows simple alternative example of generating a dashboard from static table of metrics.
Helps people get started faster
Unsure about CHANGELOG format

Table driven example with simple upload script

---

CHANGELOG.rst
grafanalib/core.py
grafanalib/tests/test_core.py

What does this do?
Fix a small bug in the nameFilter field of the AlertList panel, add a test for the class and expand its' documentation.

Fix name filter field.

---

CHANGELOG.rst
setup.py

Prep for v0.5.12 release

---

CHANGELOG.rst
setup.py

Prep v0.5.13

---

CHANGELOG.rst
grafanalib/core.py

Add colour overides to pie chart and add missing X Axis class attibutes

---

MAINTAINERS

I am moving on from Weaveworks.

Remove Bryan Boreham as maintainer

---

MAINTAINERS

See https://github.com/fluxcd/flux/blob/master/MAINTAINERS as an example

add myself to maintainers, change format to MAINTAINERS files of Flux

---

CHANGELOG.rst
docs/CONTRIBUTING.rst
grafanalib/core.py
grafanalib/tests/test_core.py

Add Worldmap panel
https://grafana.com/grafana/plugins/grafana-worldmap-panel/

Add worldmap panel

---

grafanalib/core.py

Clean up the docs: removing duplications and fix sphinx rendering issues 
No functional changes made.

Clean up code docs

---

CHANGELOG.rst
grafanalib/core.py

Added a number of missing attributes and missing documentation
Closes #379

Fill gradient

---

CHANGELOG.rst
grafanalib/core.py

I fixed this by running
'python setup.py install --user' and 'make html -C docs'
a couple of times.
Signed-off-by: Daniel Holbach <daniel@weave.works>

Fix some sphinx errors

---

grafanalib/elasticsearch.py

Add documentation for elasticsearch orderBy

---

grafanalib/_gen.py

Fixed grammar error

---

docs/CODE_OF_CONDUCT.rst

quote email to help link checker DTRT

quote email to help link checker

---

CHANGELOG.rst
docs/requirements.txt
grafanalib/core.py

This ensures that the selected value is set, for templating, I was finding that without setting selected the templating just didn't work when I loaded my dashboard.
I think that this works to help resolve https://github.com/weaveworks/grafanalib/issues/110
In my case, I 'm using the following template, and it's working as I would expect:
` Template(
dataSource="Health",
name="Host", 
refresh=2,
query={"find": "terms", "field": "host.keyword"}, 
) `
I've not had time to look in detail on the self.type == 'custom side' side of the if. But I can see that selected is getting set, so I don't think that case has this issue.

Templating

---

CHANGELOG.rst
grafanalib/core.py
grafanalib/tests/test_core.py

Adds color option for StatMapping(s).
To be able to change the color while mapping.

Stat value mappings with color option

---

CHANGELOG.rst
grafanalib/core.py
grafanalib/tests/test_core.py
grafanalib/validators.py

Adds basic support for Discrete https://grafana.com/grafana/plugins/natel-discrete-panel/ including panel itself and color mappings (DiscreteColorMappingItem to keep things tidy).
Adds "Discrete".
Discrete inherits from Panel to keep the changes small.
- How extensiv are you testing?
- Do these tests suffice?
- Any suggestions to use pre-existing features instead of DiscreteColorMappingItem?

Discrete panel

---

.gitignore
CHANGELOG.rst
grafanalib/core.py
grafanalib/tests/test_core.py

Adds additional options for Discrete panel.
Makes the Dicrete panel more customizable.
Had to shuffel some classes around. Git represents that quite ugly :/

Discrete options

---

CHANGELOG.rst
grafanalib/core.py
grafanalib/tests/test_core.py

Extends the ``SeriesOverride`` options.
Especially add ``fillBelowTo`` and ``fill`` to ``SeriesOverride``.

Extend SeriesOverride

---

CHANGELOG.rst
grafanalib/core.py

Added support for auto panels ids to AlertList panel

---

CHANGELOG.rst
grafanalib/core.py

Added fileds to Stat panel because it was not possible to set it.
Where values were not displayed in the Stat panel, fields needed to be set.

Add support for fields value in Stat panel

---

CHANGELOG.rst
grafanalib/core.py
grafanalib/tests/test_core.py

Extends the SeriesOverride options by dashes and Z-index.
More functionality.

Extend SeriesOverride (dashes, Z-index)

---

CHANGELOG.rst
grafanalib/core.py
grafanalib/tests/test_core.py

Add support for Histogram panel

---

docs/getting-started.rst
grafanalib/core.py
grafanalib/tests/examples/example.dashboard.py

Update example dashboard to latest features and work on vanila grafana install

---

CHANGELOG.rst
grafanalib/formatunits.py

This starts by adding the new Boolean unit formats, but also adds other formats that I noticed were missing.  There are likely still some missing, like in the currency section.
Fewer missing options, which are available when manually creating a dashboard.
It would sure be nice to auto-generate this file by grabbing the upstream file and processing it, but I don't have any good ideas for generating nice names (or keeping the current constant names).

Add missing format units

---

CHANGELOG.rst
grafanalib/core.py

Fix broken links

---

CHANGELOG.rst
setup.py

Prep v0.7.0 release

---

.github/workflows/run-tests.yml
README.rst

Update readme doc tag from latest to main branch

---

grafanalib/elasticsearch.py

Thank you very much for this great library.
It is very useful for me.
BTW, I found some typos, so I have created this PR.
Fixed typos of description in grafanalib/elasticsearch.py.
It is useful for developers.

fix: typos of description in grafanalib/elasticsearch.py

---

docs/getting-started.rst
setup.py
tox.ini

update to conform and test against all current pythons

---

MAINTAINERS

I haven't found much time for grafanalib lately. It was a big pleasure to work together with all of you. All the best!
cc @JamesGibo

Remove myself from maintainers.

---

.github/workflows/check-sphinx-and-links.yml

Bump CI python version to 3.9

---

.github/workflows/publish-to-pypi.yml

Bump pypi build to use python 3.10
